CREATE TABLE "cached_tools" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cached_tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tool_name" text NOT NULL,
	"description" text,
	"parameters" jsonb DEFAULT '{}',
	"server_request_url" text NOT NULL,
	"customer_email" text,
	"platform_customer_id" bigint,
	CONSTRAINT "cached_tools_unique_tool_customer" UNIQUE("tool_name","customer_email","platform_customer_id")
);
--> statement-breakpoint
ALTER TABLE "cached_tools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "cached_tools_customer_email_idx" ON "cached_tools" USING btree ("customer_email");--> statement-breakpoint
CREATE INDEX "cached_tools_platform_customer_id_idx" ON "cached_tools" USING btree ("platform_customer_id");--> statement-breakpoint
CREATE INDEX "cached_tools_tool_name_idx" ON "cached_tools" USING btree ("tool_name");